routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\CharacterDeskripsiController;
use App\Http\Controllers\CharacterDibangunController;
use App\Http\Controllers\UserController;
use App\Models\Character;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [UserController::class, 'welcome'])->middleware('auth')->name('welcome');
Route::get('/profile', [UserController::class, 'profile'])->middleware('auth')->name('profile');
Route::post('/avatar-post', [UserController::class, 'update_profile'])->middleware('auth')->name('profile.post');
Route::post('/change-passowrd', [ChangePasswordController::class, 'changePassword'])->name('change.password');
Route::get('/print-character/{id}',[CharacterController::class, 'cetak'])->middleware('auth')->name('cetak');
Route::get('/characters/export/', [CharacterController::class, 'export'])->name('export');

Route::get('/karakter/rombel', [CharacterController::class, 'rombel'])->middleware('auth')->name('rombel');

Route::get('/karakter/kelas-bdp', [CharacterController::class, 'kelas_bdp'])->middleware('auth')->name('kelas.bdp');
Route::get('/karakter/kelas-mmd', [CharacterController::class, 'kelas_mmd'])->middleware('auth')->name('kelas.mmd');
Route::get('/karakter/kelas-otkp', [CharacterController::class, 'kelas_otkp'])->middleware('auth')->name('kelas.otkp');
Route::get('/karakter/kelas-htl', [CharacterController::class, 'kelas_htl'])->middleware('auth')->name('kelas.htl');
Route::get('/karakter/kelas-rpl', [CharacterController::class, 'kelas_rpl'])->middleware('auth')->name('kelas.rpl');
Route::get('/karakter/kelas-tbg', [CharacterController::class, 'kelas_tbg'])->middleware('auth')->name('kelas.tbg');
Route::get('/karakter/kelas-tkj', [CharacterController::class, 'kelas_tkj'])->middleware('auth')->name('kelas.tkj');

Route::get('/karakter/kelas-bdp-x', [CharacterController::class, 'kelas_x_bdp'])->middleware('auth')->name('kelas.x.bdp');
Route::get('/karakter/kelas-bdp-xi', [CharacterController::class, 'kelas_xi_bdp'])->middleware('auth')->name('kelas.xi.bdp');
Route::get('/karakter/kelas-bdp-xii', [CharacterController::class, 'kelas_xii_bdp'])->middleware('auth')->name('kelas.xii.bdp');

Route::get('/karakter/kelas-htl-x', [CharacterController::class, 'kelas_x_htl'])->middleware('auth')->name('kelas.x.htl');
Route::get('/karakter/kelas-htl-xi', [CharacterController::class, 'kelas_xi_htl'])->middleware('auth')->name('kelas.xi.htl');
Route::get('/karakter/kelas-htl-xii', [CharacterController::class, 'kelas_xii_htl'])->middleware('auth')->name('kelas.xii.htl');

Route::get('/karakter/kelas-mmd-x', [CharacterController::class, 'kelas_x_mmd'])->middleware('auth')->name('kelas.x.mmd');
Route::get('/karakter/kelas-mmd-xi', [CharacterController::class, 'kelas_xi_mmd'])->middleware('auth')->name('kelas.xi.mmd');
Route::get('/karakter/kelas-mmd-xii', [CharacterController::class, 'kelas_xii_mmd'])->middleware('auth')->name('kelas.xii.mmd');

Route::get('/karakter/kelas-otkp-x', [CharacterController::class, 'kelas_x_otkp'])->middleware('auth')->name('kelas.x.otkp');
Route::get('/karakter/kelas-otkp-xi', [CharacterController::class, 'kelas_xi_otkp'])->middleware('auth')->name('kelas.xi.otkp');
Route::get('/karakter/kelas-otkp-xii', [CharacterController::class, 'kelas_xii_otkp'])->middleware('auth')->name('kelas.xii.otkp');

Route::get('/karakter/kelas-rpl-x', [CharacterController::class, 'kelas_x_rpl'])->middleware('auth')->name('kelas.x.rpl');
Route::get('/karakter/kelas-rpl-xi', [CharacterController::class, 'kelas_xi_rpl'])->middleware('auth')->name('kelas.xi.rpl');
Route::get('/karakter/kelas-rpl-xii', [CharacterController::class, 'kelas_xii_rpl'])->middleware('auth')->name('kelas.xii.rpl');

Route::get('/karakter/kelas-tbg-x', [CharacterController::class, 'kelas_x_tbg'])->middleware('auth')->name('kelas.x.tbg');
Route::get('/karakter/kelas-tbg-xi', [CharacterController::class, 'kelas_xi_tbg'])->middleware('auth')->name('kelas.xi.tbg');
Route::get('/karakter/kelas-tbg-xii', [CharacterController::class, 'kelas_xii_tbg'])->middleware('auth')->name('kelas.xii.tbg');

Route::get('/karakter/kelas-tkj-x', [CharacterController::class, 'kelas_x_tkj'])->middleware('auth')->name('kelas.x.tkj');
Route::get('/karakter/kelas-tkj-xi', [CharacterController::class, 'kelas_xi_tkj'])->middleware('auth')->name('kelas.xi.tkj');
Route::get('/karakter/kelas-tkj-xii', [CharacterController::class, 'kelas_xii_tkj'])->middleware('auth')->name('kelas.xii.tkj');


Route::resource('characters', CharacterController::class)->middleware('auth');
Route::resource('character-dibangun', CharacterDibangunController::class)->middleware('auth');

app/Models/CharacterDibangun.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CharacterDibangun extends Model
{
    use HasFactory;

    protected $table = 'character_dibanguns';
    protected $guarded = [];
}

app/Http/Controllers/CharacterDibangunController.php
<?php

namespace App\Http\Controllers;

use App\Models\CharacterDibangun;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;

class CharacterDibangunController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = CharacterDibangun::where('alias', 'LIKE', "%{$search}%")->paginate(5);
        }else {
            $characters = CharacterDibangun::latest()->paginate(5);
        }

        return view('character_dibangun.index', [
            'characters' => $characters,
        ])
        ->with('i');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('character_dibangun.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'alias' => 'required|max:32',
            'judul' => 'required|max:32',
            'deskripsi' => 'required',
        ]);

        CharacterDibangun::create($request->all());

        return redirect()->route('character-dibangun.index')->with('success', 'Karakter Dibangun berhasil dibuat !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $character = CharacterDibangun::findOrFail($id);

        return view('character_dibangun.edit', compact('character'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'alias' => 'required|max:32',
            'judul' => 'required|max:32',
            'deskripsi' => 'required',
        ]);

        $character = CharacterDibangun::findOrFail($id);
        $character->update($request->all());

        return redirect()->route('character-dibangun.index')->with('success', 'Karakter Dibangun berhasil diperbarui !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $character = CharacterDibangun::findOrFail($id);
        $character->delete();

        return redirect()->route('character-dibangun.index')->with('success', 'Karakter Dibangun berhasil dihapus');
    }
}

resources/views/character_dibangun/create.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Form Validation</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index-2.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Forms</a>
                  </li>
                  <li class="breadcrumb-item active">Form Validation
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
            <div class="dropdown">
              <a class="btn-icon btn btn-danger btn-round btn-sm dropdown-toggle" href="{{ route('character-dibangun.index') }}">Back</a>
            </div>
          </div>
        </div>
      </div>
      <div class="content-body"><!-- Validation -->
<section class="bs-validation">
<div class="row">
  <!-- Bootstrap Validation -->
  <div class="col-md-12 col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Bootstrap Validation</h4>
      </div>
      <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form class="needs-validation" method="POST" action="{{ route('character-dibangun.store') }}">
            @csrf
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="form-label" for="alias">Alias</label>

                    <input
                      type="text"
                      id="alias"
                      class="form-control"
                      placeholder="Masukkan Alias"
                      name="alias"
                      aria-describedby="basic-addon-name"
                      required
                    />
                </div>
                <div class="form-group col-md-6">
                    <label class="form-label" for="judul">Judul</label>

                    <input
                      type="text"
                      id="judul"
                      class="form-control"
                      placeholder="Masukkan Judul"
                      name="judul"
                      aria-describedby="basic-addon-name"
                      required
                    />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="form-label" for="deskripsi">Deskripsi</label>

                    <textarea class="form-control" name="deskripsi" id="deskripsi" cols="30" rows="10" placeholder="Masukkan Deskripsi"></textarea>
                </div>
            </div>
          <div class="row">
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /Bootstrap Validation -->
</div>
</section>
<!-- /Validation -->

      </div>
    </div>
  </div>
@endsection

resources/views/character_dibangun/edit.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Form Validation</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index-2.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Forms</a>
                  </li>
                  <li class="breadcrumb-item active">Form Validation
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
            <div class="dropdown">
              <a class="btn-icon btn btn-danger btn-round btn-sm dropdown-toggle" href="{{ route('character-dibangun.index') }}">Back</a>
            </div>
          </div>
        </div>
      </div>
      <div class="content-body"><!-- Validation -->
<section class="bs-validation">
<div class="row">
  <!-- Bootstrap Validation -->
  <div class="col-md-12 col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Bootstrap Validation</h4>
      </div>
      <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form class="needs-validation" method="POST" action="{{ route('character-dibangun.update', $character->id) }}">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="form-label" for="alias">Alias</label>

                    <input
                      type="text"
                      id="alias"
                      class="form-control"
                      placeholder="Masukkan Alias"
                      name="alias"
                      aria-describedby="basic-addon-name"
                      value="{{ $character->alias }}"
                      required
                    />
                </div>
                <div class="form-group col-md-6">
                    <label class="form-label" for="judul">Judul</label>

                    <input
                      type="text"
                      id="judul"
                      class="form-control"
                      placeholder="Masukkan Judul"
                      name="judul"
                      aria-describedby="basic-addon-name"
                      value="{{ $character->judul }}"
                      required
                    />
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="form-label" for="deskripsi">Deskripsi</label>

                    <textarea class="form-control" name="deskripsi" id="deskripsi" cols="30" rows="10" placeholder="Masukkan Deskripsi">{{ $character->deskripsi }}</textarea>
                </div>
            </div>
          <div class="row">
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /Bootstrap Validation -->
</div>
</section>
<!-- /Validation -->

      </div>
    </div>
  </div>
@endsection

resources/views/character_dibangun/index.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Karakter Dibangun Table</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Karakter Dibangun
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Karakter Dibangun</h4>

      <a href="{{ route('character-dibangun.create') }}" class="btn btn-success">+ Tambah</a>

    </div>
    <form class="d-flex" action="{{ route('character-dibangun.index') }}" method="GET">
        {{ csrf_field() }}
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari . . . "></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
        {{-- <a class="btn btn-dark ag-grid-export-btn ml-auto mr-2" href="{{ route('export') }}">Export as Excel</a> --}}
    </form>

    <div class="card-body">
    </div>

    <div class="table-responsive">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>No</th>
            <th width="500px">Alias</th>
            <th width="500px">Judul</th>
            <th width="500px">Deskripsi</th>
            <th width="500px">Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($characters as $character)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $character->alias }}</td>
                <td>{{ $character->judul }}</td>
                <td>{{ $character->deskripsi }}</td>
                <td>
                        <form action="{{ route('character-dibangun.destroy',$character->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('character-dibangun.edit', $character->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="10" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $characters->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection