routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\CharacterDeskripsiController;
use App\Http\Controllers\CharacterDibangunController;
use App\Http\Controllers\UserController;
use App\Models\Character;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [UserController::class, 'welcome'])->middleware('auth')->name('welcome');
Route::get('/profile', [UserController::class, 'profile'])->middleware('auth')->name('profile');
Route::post('/avatar-post', [UserController::class, 'update_profile'])->middleware('auth')->name('profile.post');
Route::post('/change-passowrd', [ChangePasswordController::class, 'changePassword'])->name('change.password');
Route::get('/print-character/{id}',[CharacterController::class, 'cetak'])->middleware('auth')->name('cetak');
Route::get('/characters/export/', [CharacterController::class, 'export'])->name('export');

Route::get('/karakter/rombel', [CharacterController::class, 'rombel'])->middleware('auth')->name('rombel');

Route::get('/karakter/kelas-bdp', [CharacterController::class, 'kelas_bdp'])->middleware('auth')->name('kelas.bdp');
Route::get('/karakter/kelas-mmd', [CharacterController::class, 'kelas_mmd'])->middleware('auth')->name('kelas.mmd');
Route::get('/karakter/kelas-otkp', [CharacterController::class, 'kelas_otkp'])->middleware('auth')->name('kelas.otkp');
Route::get('/karakter/kelas-htl', [CharacterController::class, 'kelas_htl'])->middleware('auth')->name('kelas.htl');
Route::get('/karakter/kelas-rpl', [CharacterController::class, 'kelas_rpl'])->middleware('auth')->name('kelas.rpl');
Route::get('/karakter/kelas-tbg', [CharacterController::class, 'kelas_tbg'])->middleware('auth')->name('kelas.tbg');
Route::get('/karakter/kelas-tkj', [CharacterController::class, 'kelas_tkj'])->middleware('auth')->name('kelas.tkj');

Route::get('/karakter/kelas-bdp-x', [CharacterController::class, 'kelas_x_bdp'])->middleware('auth')->name('kelas.x.bdp');
Route::get('/karakter/kelas-bdp-xi', [CharacterController::class, 'kelas_xi_bdp'])->middleware('auth')->name('kelas.xi.bdp');
Route::get('/karakter/kelas-bdp-xii', [CharacterController::class, 'kelas_xii_bdp'])->middleware('auth')->name('kelas.xii.bdp');

Route::get('/karakter/kelas-htl-x', [CharacterController::class, 'kelas_x_htl'])->middleware('auth')->name('kelas.x.htl');
Route::get('/karakter/kelas-htl-xi', [CharacterController::class, 'kelas_xi_htl'])->middleware('auth')->name('kelas.xi.htl');
Route::get('/karakter/kelas-htl-xii', [CharacterController::class, 'kelas_xii_htl'])->middleware('auth')->name('kelas.xii.htl');

Route::get('/karakter/kelas-mmd-x', [CharacterController::class, 'kelas_x_mmd'])->middleware('auth')->name('kelas.x.mmd');
Route::get('/karakter/kelas-mmd-xi', [CharacterController::class, 'kelas_xi_mmd'])->middleware('auth')->name('kelas.xi.mmd');
Route::get('/karakter/kelas-mmd-xii', [CharacterController::class, 'kelas_xii_mmd'])->middleware('auth')->name('kelas.xii.mmd');

Route::get('/karakter/kelas-otkp-x', [CharacterController::class, 'kelas_x_otkp'])->middleware('auth')->name('kelas.x.otkp');
Route::get('/karakter/kelas-otkp-xi', [CharacterController::class, 'kelas_xi_otkp'])->middleware('auth')->name('kelas.xi.otkp');
Route::get('/karakter/kelas-otkp-xii', [CharacterController::class, 'kelas_xii_otkp'])->middleware('auth')->name('kelas.xii.otkp');

Route::get('/karakter/kelas-rpl-x', [CharacterController::class, 'kelas_x_rpl'])->middleware('auth')->name('kelas.x.rpl');
Route::get('/karakter/kelas-rpl-xi', [CharacterController::class, 'kelas_xi_rpl'])->middleware('auth')->name('kelas.xi.rpl');
Route::get('/karakter/kelas-rpl-xii', [CharacterController::class, 'kelas_xii_rpl'])->middleware('auth')->name('kelas.xii.rpl');

Route::get('/karakter/kelas-tbg-x', [CharacterController::class, 'kelas_x_tbg'])->middleware('auth')->name('kelas.x.tbg');
Route::get('/karakter/kelas-tbg-xi', [CharacterController::class, 'kelas_xi_tbg'])->middleware('auth')->name('kelas.xi.tbg');
Route::get('/karakter/kelas-tbg-xii', [CharacterController::class, 'kelas_xii_tbg'])->middleware('auth')->name('kelas.xii.tbg');

Route::get('/karakter/kelas-tkj-x', [CharacterController::class, 'kelas_x_tkj'])->middleware('auth')->name('kelas.x.tkj');
Route::get('/karakter/kelas-tkj-xi', [CharacterController::class, 'kelas_xi_tkj'])->middleware('auth')->name('kelas.xi.tkj');
Route::get('/karakter/kelas-tkj-xii', [CharacterController::class, 'kelas_xii_tkj'])->middleware('auth')->name('kelas.xii.tkj');


Route::resource('characters', CharacterController::class)->middleware('auth');
Route::resource('character-dibangun', CharacterDibangunController::class)->middleware('auth');

resources/views/admin/footer.blade.php
<div class="customizer-footer px-2">
    <p class="font-weight-bold">Footer Type</p>
    <div class="d-flex">
      <div class="custom-control custom-radio mr-1">
        <input type="radio" id="footer-type-sticky" name="footerType" class="custom-control-input" />
        <label class="custom-control-label" for="footer-type-sticky">Sticky</label>
      </div>
      <div class="custom-control custom-radio mr-1">
        <input type="radio" id="footer-type-static" name="footerType" class="custom-control-input" checked />
        <label class="custom-control-label" for="footer-type-static">Static</label>
      </div>
      <div class="custom-control custom-radio mr-1">
        <input type="radio" id="footer-type-hidden" name="footerType" class="custom-control-input" />
        <label class="custom-control-label" for="footer-type-hidden">Hidden</label>
      </div>
    </div>
  </div>
</div>

    </div>
    <!-- End: Customizer-->

    <!-- Buynow Button-->
    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light">
      <p class="clearfix mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">Copyricght  &copy; 2021<a class="ml-25" href="https://smkwikrama.sch.id/" target="_blank">Wikrama</a><span class="d-none d-sm-inline-block">, All rights Reserved</span></span></p>
    </footer>
    <button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>

resources/views/admin/head.blade.php
<!-- Mirrored from pixinvent.com/demo/vuexy-html-bootstrap-admin-template/html/ltr/vertical-menu-template/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Feb 2021 02:48:13 GMT -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>Dashboard - Wikrama</title>
    <link rel="apple-touch-icon" href="../../../app-assets/images/ico/apple-icon-120.html">
    <link rel="shortcut icon" type="image/x-icon" href="../../app-assets/images/logowk.png">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/vendors.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/charts/apexcharts.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.min.css') }}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/bootstrap-extended.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/colors.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/components.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/themes/dark-layout.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/themes/bordered-layout.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/themes/semi-dark-layout.min.css') }}">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/core/menu/menu-types/vertical-menu.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/pages/dashboard-ecommerce.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/charts/chart-apex.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-toastr.min.css') }}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css') }}">
    <!-- END: Custom CSS-->

  </head>

resources/views/admin/header.blade.php
<nav class="header-navbar navbar navbar-expand-lg align-items-center floating-nav navbar-light navbar-shadow">
    <div class="navbar-container d-flex content">
      <div class="bookmark-wrapper d-flex align-items-center">
        <ul class="nav navbar-nav d-xl-none">
          <li class="nav-item"><a class="nav-link menu-toggle" href="javascript:void(0);"><i class="ficon" data-feather="menu"></i></a></li>
        </ul>
      </div>
      <ul class="nav navbar-nav align-items-center ml-auto">
        <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-style"><i class="ficon" data-feather="moon"></i></a></li>


        <li class="nav-item dropdown dropdown-user"><a class="nav-link dropdown-toggle dropdown-user-link" id="dropdown-user" href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="user-nav d-sm-flex d-none"><span class="user-name font-weight-bolder">{{ Auth::user()->name }}</span><span class="user-status">Admin</span></div><span class="avatar"><img class="round" src="../../uploads/avatars/{{ Auth::user()->avatar }}" alt="avatar" height="40" width="40"><span class="avatar-status-online"></span></span></a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-user"><a class="dropdown-item" href="{{ route('profile') }}"><i class="mr-50" data-feather="user"></i> Profile</a>
            <div class="dropdown-divider"></div><a class="dropdown-item" href="{{ route('logout') }}"
            onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();"><i class="mr-50" data-feather="power"></i> Logout</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <ul class="main-search-list-defaultlist d-none">
    <li class="d-flex align-items-center"><a href="javascript:void(0);">
        <h6 class="section-label mt-75 mb-0">Files</h6></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between w-100" href="app-file-manager.html">
        <div class="d-flex">
          <div class="mr-75"><img src="../../../app-assets/images/icons/xls.png" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">Two new item submitted</p><small class="text-muted">Marketing Manager</small>
          </div>
        </div><small class="search-data-size mr-50 text-muted">&apos;17kb</small></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between w-100" href="app-file-manager.html">
        <div class="d-flex">
          <div class="mr-75"><img src="../../../app-assets/images/icons/jpg.png" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">52 JPG file Generated</p><small class="text-muted">FontEnd Developer</small>
          </div>
        </div><small class="search-data-size mr-50 text-muted">&apos;11kb</small></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between w-100" href="app-file-manager.html">
        <div class="d-flex">
          <div class="mr-75"><img src="../../../app-assets/images/icons/pdf.png" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">25 PDF File Uploaded</p><small class="text-muted">Digital Marketing Manager</small>
          </div>
        </div><small class="search-data-size mr-50 text-muted">&apos;150kb</small></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between w-100" href="app-file-manager.html">
        <div class="d-flex">
          <div class="mr-75"><img src="../../../app-assets/images/icons/doc.png" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">Anna_Strong.doc</p><small class="text-muted">Web Designer</small>
          </div>
        </div><small class="search-data-size mr-50 text-muted">&apos;256kb</small></a></li>
    <li class="d-flex align-items-center"><a href="javascript:void(0);">
        <h6 class="section-label mt-75 mb-0">Members</h6></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between py-50 w-100" href="app-user-view.html">
        <div class="d-flex align-items-center">
          <div class="avatar mr-75"><img src="../../../app-assets/images/portrait/small/avatar-s-8.jpg" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">John Doe</p><small class="text-muted">UI designer</small>
          </div>
        </div></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between py-50 w-100" href="app-user-view.html">
        <div class="d-flex align-items-center">
          <div class="avatar mr-75"><img src="../../../app-assets/images/portrait/small/avatar-s-1.jpg" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">Michal Clark</p><small class="text-muted">FontEnd Developer</small>
          </div>
        </div></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between py-50 w-100" href="app-user-view.html">
        <div class="d-flex align-items-center">
          <div class="avatar mr-75"><img src="../../../app-assets/images/portrait/small/avatar-s-14.jpg" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">Milena Gibson</p><small class="text-muted">Digital Marketing Manager</small>
          </div>
        </div></a></li>
    <li class="auto-suggestion"><a class="d-flex align-items-center justify-content-between py-50 w-100" href="app-user-view.html">
        <div class="d-flex align-items-center">
          <div class="avatar mr-75"><img src="../../../app-assets/images/portrait/small/avatar-s-6.jpg" alt="png" height="32"></div>
          <div class="search-data">
            <p class="search-data-title mb-0">Anna Strong</p><small class="text-muted">Web Designer</small>
          </div>
        </div></a></li>
  </ul>
  <ul class="main-search-list-defaultlist-other-list d-none">
    <li class="auto-suggestion justify-content-between"><a class="d-flex align-items-center justify-content-between w-100 py-50">
        <div class="d-flex justify-content-start"><span class="mr-75" data-feather="alert-circle"></span><span>No results found.</span></div></a></li>
  </ul>

resources/views/admin/main.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="navbar-header">
      <ul class="nav navbar-nav flex-row">
        <li class="nav-item mr-auto"><a class="navbar-brand" href="#"><img src="../../app-assets/images/logowk.png" alt="logo wk" height="35">
            <h2 class="brand-text">Wikrama</h2></a></li>
        <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i></a></li>
      </ul>
    </div>
    <div class="shadow-bottom"></div>
    <div class="main-menu-content">
      <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
        <li class=" nav-item"><a class="d-flex align-items-center" href="{{ route('welcome') }}"><i data-feather="home"></i><span class="menu-title text-truncate" data-i18n="Dashboards">Dashboards</span></a>
        </li>
        </li>
        <li class=" navigation-header"><span data-i18n="Forms &amp; Tables">Forms &amp; Tables</span><i data-feather="more-horizontal"></i>
        </li>
        <li class=" nav-item"><a class="d-flex align-items-center" href="{{ route('characters.create') }}"><i data-feather="server"></i><span class="menu-title text-truncate" data-i18n="Table">Tambah Data</span></a>
        </li>
         <li class=" nav-item"><a class="d-flex align-items-center" href="{{ route('character-dibangun.index') }}"><i data-feather="server"></i><span class="menu-title text-truncate" data-i18n="Table">Tambah Karakter Dibangun</span></a>
        </li>
        <li class=" nav-item"><a class="d-flex align-items-center" href="{{ route('rombel') }}"><i data-feather="server"></i><span class="menu-title text-truncate" data-i18n="Table">List Data</span></a>
        </li>
    </div>
  </div>

resources/views/admin/scripts.blade.php
<!-- BEGIN: Vendor JS-->
<script src="{{ asset('app-assets/vendors/js/vendors.min.js') }}"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{{ asset('app-assets/vendors/js/charts/apexcharts.min.js') }}"></script>
<script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="{{ asset('app-assets/js/core/app-menu.min.js') }}"></script>
<script src="{{ asset('app-assets/js/core/app.min.js') }}"></script>
<script src="{{ asset('app-assets/js/scripts/customizer.min.js') }}"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page JS-->
<script src="{{ asset('app-assets/js/scripts/pages/dashboard-ecommerce.min.js') }}"></script>
<!-- END: Page JS-->

<script>
  $(window).on('load',  function(){
    if (feather) {
      feather.replace({ width: 14, height: 14 });
    }
  })
</script>