routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\CharacterDeskripsiController;
use App\Http\Controllers\CharacterDibangunController;
use App\Http\Controllers\UserController;
use App\Models\Character;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [UserController::class, 'welcome'])->middleware('auth')->name('welcome');
Route::get('/profile', [UserController::class, 'profile'])->middleware('auth')->name('profile');
Route::post('/avatar-post', [UserController::class, 'update_profile'])->middleware('auth')->name('profile.post');
Route::post('/change-passowrd', [ChangePasswordController::class, 'changePassword'])->name('change.password');
Route::get('/print-character/{id}',[CharacterController::class, 'cetak'])->middleware('auth')->name('cetak');
Route::get('/characters/export/', [CharacterController::class, 'export'])->name('export');

Route::get('/karakter/rombel', [CharacterController::class, 'rombel'])->middleware('auth')->name('rombel');

Route::get('/karakter/kelas-bdp', [CharacterController::class, 'kelas_bdp'])->middleware('auth')->name('kelas.bdp');
Route::get('/karakter/kelas-mmd', [CharacterController::class, 'kelas_mmd'])->middleware('auth')->name('kelas.mmd');
Route::get('/karakter/kelas-otkp', [CharacterController::class, 'kelas_otkp'])->middleware('auth')->name('kelas.otkp');
Route::get('/karakter/kelas-htl', [CharacterController::class, 'kelas_htl'])->middleware('auth')->name('kelas.htl');
Route::get('/karakter/kelas-rpl', [CharacterController::class, 'kelas_rpl'])->middleware('auth')->name('kelas.rpl');
Route::get('/karakter/kelas-tbg', [CharacterController::class, 'kelas_tbg'])->middleware('auth')->name('kelas.tbg');
Route::get('/karakter/kelas-tkj', [CharacterController::class, 'kelas_tkj'])->middleware('auth')->name('kelas.tkj');

Route::get('/karakter/kelas-bdp-x', [CharacterController::class, 'kelas_x_bdp'])->middleware('auth')->name('kelas.x.bdp');
Route::get('/karakter/kelas-bdp-xi', [CharacterController::class, 'kelas_xi_bdp'])->middleware('auth')->name('kelas.xi.bdp');
Route::get('/karakter/kelas-bdp-xii', [CharacterController::class, 'kelas_xii_bdp'])->middleware('auth')->name('kelas.xii.bdp');

Route::get('/karakter/kelas-htl-x', [CharacterController::class, 'kelas_x_htl'])->middleware('auth')->name('kelas.x.htl');
Route::get('/karakter/kelas-htl-xi', [CharacterController::class, 'kelas_xi_htl'])->middleware('auth')->name('kelas.xi.htl');
Route::get('/karakter/kelas-htl-xii', [CharacterController::class, 'kelas_xii_htl'])->middleware('auth')->name('kelas.xii.htl');

Route::get('/karakter/kelas-mmd-x', [CharacterController::class, 'kelas_x_mmd'])->middleware('auth')->name('kelas.x.mmd');
Route::get('/karakter/kelas-mmd-xi', [CharacterController::class, 'kelas_xi_mmd'])->middleware('auth')->name('kelas.xi.mmd');
Route::get('/karakter/kelas-mmd-xii', [CharacterController::class, 'kelas_xii_mmd'])->middleware('auth')->name('kelas.xii.mmd');

Route::get('/karakter/kelas-otkp-x', [CharacterController::class, 'kelas_x_otkp'])->middleware('auth')->name('kelas.x.otkp');
Route::get('/karakter/kelas-otkp-xi', [CharacterController::class, 'kelas_xi_otkp'])->middleware('auth')->name('kelas.xi.otkp');
Route::get('/karakter/kelas-otkp-xii', [CharacterController::class, 'kelas_xii_otkp'])->middleware('auth')->name('kelas.xii.otkp');

Route::get('/karakter/kelas-rpl-x', [CharacterController::class, 'kelas_x_rpl'])->middleware('auth')->name('kelas.x.rpl');
Route::get('/karakter/kelas-rpl-xi', [CharacterController::class, 'kelas_xi_rpl'])->middleware('auth')->name('kelas.xi.rpl');
Route::get('/karakter/kelas-rpl-xii', [CharacterController::class, 'kelas_xii_rpl'])->middleware('auth')->name('kelas.xii.rpl');

Route::get('/karakter/kelas-tbg-x', [CharacterController::class, 'kelas_x_tbg'])->middleware('auth')->name('kelas.x.tbg');
Route::get('/karakter/kelas-tbg-xi', [CharacterController::class, 'kelas_xi_tbg'])->middleware('auth')->name('kelas.xi.tbg');
Route::get('/karakter/kelas-tbg-xii', [CharacterController::class, 'kelas_xii_tbg'])->middleware('auth')->name('kelas.xii.tbg');

Route::get('/karakter/kelas-tkj-x', [CharacterController::class, 'kelas_x_tkj'])->middleware('auth')->name('kelas.x.tkj');
Route::get('/karakter/kelas-tkj-xi', [CharacterController::class, 'kelas_xi_tkj'])->middleware('auth')->name('kelas.xi.tkj');
Route::get('/karakter/kelas-tkj-xii', [CharacterController::class, 'kelas_xii_tkj'])->middleware('auth')->name('kelas.xii.tkj');


Route::resource('characters', CharacterController::class)->middleware('auth');
Route::resource('character-dibangun', CharacterDibangunController::class)->middleware('auth');

resources/views/kelas/kelas-tbg.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-12 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Pilih Jurusan</h2>
              <a class="btn btn-primary btn-sm float-right" href="{{ route('rombel') }}">Back</a>
            </div>
          </div>
        </div>
      </div>

            <div class="text-center">
                <a class="btn btn-primary btn-lg col-md-8 mt-5" href="{{ route('kelas.x.tbg') }}">Kelas X</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.xi.tbg') }}">Kelas XI</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.xii.tbg') }}">Kelas XII</a>
            </div>


      </div>
    </div>
  </div>
@endsection

resources/views/kelas/kelas-tkj.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-12 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Pilih Jurusan</h2>
              <a class="btn btn-primary btn-sm float-right" href="{{ route('rombel') }}">Back</a>
            </div>
          </div>
        </div>
      </div>

            <div class="text-center">
                <a class="btn btn-primary btn-lg col-md-8 mt-5" href="{{ route('kelas.x.tkj') }}">Kelas X</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.xi.tkj') }}">Kelas XI</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.xii.tkj') }}">Kelas XII</a>
            </div>


      </div>
    </div>
  </div>
@endsection

resources/views/kelas/kelas-x-mmd.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Karakter Tables</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Karakter
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Karakter</h4>

      <a href="{{ route('characters.create') }}" class="btn btn-success">+ Tambah</a>

    </div>
    <form class="d-flex" action="{{ route('kelas.x.mmd') }}" method="GET">
        {{ csrf_field() }}
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari nis siswa"></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
        <a class="btn btn-dark ag-grid-export-btn ml-auto mr-2" href="{{ route('export') }}">Export as Excel</a>
    </form>

    <div class="card-body">
    </div>

    <div class="table-responsive">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>NIS</th>
            <th>Nama</th>
            <th>Alias 1</th>
            <th>Alias 2</th>
            <th>Alias 3</th>
            <th>Alias 4</th>
            <th>Alias 5</th>
            <th>Catatan</th>
            <th>Tanggal Terbit</th>
            <th>Jurusan</th>
            <th>Kelas</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($characters as $character)
            <tr>
                <td>{{ $character->nis }}</td>
                <td>{{ $character->nama }}</td>
                <td>{{ $character->alias1->alias }}</td>
                <td>{{ $character->alias2->alias }}</td>
                <td>{{ $character->alias3->alias }}</td>
                <td>{{ $character->alias4->alias }}</td>
                <td>{{ $character->alias5->alias }}</td>
                <td>{{ $character->catatan }}</td>
                <td>{{ Carbon\Carbon::parse($character->penerbitan)->isoFormat('D MMMM Y') }}</td>
                <td>{{ $character->jurusan }}</td>
                <td>{{ $character->kelas }}</td>
                <td>
                        <form action="{{ route('characters.destroy',$character->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('characters.edit',$character->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>
                                  <a class="btn btn-success" href="{{ route('cetak',$character->id) }}">
                                    <i data-feather="upload" class="mr-50"></i>
                                    <span>Print</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="12" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $characters->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection

resources/views/kelas/kelas-x-otkp.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Karakter Tables</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Karakter
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Karakter</h4>

      <a href="{{ route('characters.create') }}" class="btn btn-success">+ Tambah</a>

    </div>
    <form class="d-flex" action="{{ route('kelas.x.otkp') }}" method="GET">
        {{ csrf_field() }}
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari nis siswa"></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
        <a class="btn btn-dark ag-grid-export-btn ml-auto mr-2" href="{{ route('export') }}">Export as Excel</a>
    </form>

    <div class="card-body">
    </div>

    <div class="table-responsive">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>NIS</th>
            <th>Nama</th>
            <th>Alias 1</th>
            <th>Alias 2</th>
            <th>Alias 3</th>
            <th>Alias 4</th>
            <th>Alias 5</th>
            <th>Catatan</th>
            <th>Tanggal Terbit</th>
            <th>Jurusan</th>
            <th>Kelas</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($characters as $character)
            <tr>
                <td>{{ $character->nis }}</td>
                <td>{{ $character->nama }}</td>
                <td>{{ $character->alias1->alias }}</td>
                <td>{{ $character->alias2->alias }}</td>
                <td>{{ $character->alias3->alias }}</td>
                <td>{{ $character->alias4->alias }}</td>
                <td>{{ $character->alias5->alias }}</td>
                <td>{{ $character->catatan }}</td>
                <td>{{ Carbon\Carbon::parse($character->penerbitan)->isoFormat('D MMMM Y') }}</td>
                <td>{{ $character->jurusan }}</td>
                <td>{{ $character->kelas }}</td>
                <td>
                        <form action="{{ route('characters.destroy',$character->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('characters.edit',$character->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>
                                  <a class="btn btn-success" href="{{ route('cetak',$character->id) }}">
                                    <i data-feather="upload" class="mr-50"></i>
                                    <span>Print</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="12" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $characters->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection

resources/views/kelas/kelas-x-tkj.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Karakter Tables</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Karakter
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Karakter</h4>

      <a href="{{ route('characters.create') }}" class="btn btn-success">+ Tambah</a>

    </div>
    <form class="d-flex" action="{{ route('kelas.x.tkj') }}" method="GET">
        {{ csrf_field() }}
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari nis siswa"></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
        <a class="btn btn-dark ag-grid-export-btn ml-auto mr-2" href="{{ route('export') }}">Export as Excel</a>
    </form>

    <div class="card-body">
    </div>

    <div class="table-responsive">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>NIS</th>
            <th>Nama</th>
            <th>Alias 1</th>
            <th>Alias 2</th>
            <th>Alias 3</th>
            <th>Alias 4</th>
            <th>Alias 5</th>
            <th>Catatan</th>
            <th>Tanggal Terbit</th>
            <th>Jurusan</th>
            <th>Kelas</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($characters as $character)
            <tr>
                <td>{{ $character->nis }}</td>
                <td>{{ $character->nama }}</td>
                <td>{{ $character->alias1->alias }}</td>
                <td>{{ $character->alias2->alias }}</td>
                <td>{{ $character->alias3->alias }}</td>
                <td>{{ $character->alias4->alias }}</td>
                <td>{{ $character->alias5->alias }}</td>
                <td>{{ $character->catatan }}</td>
                <td>{{ Carbon\Carbon::parse($character->penerbitan)->isoFormat('D MMMM Y') }}</td>
                <td>{{ $character->jurusan }}</td>
                <td>{{ $character->kelas }}</td>
                <td>
                        <form action="{{ route('characters.destroy',$character->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('characters.edit',$character->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>
                                  <a class="btn btn-success" href="{{ route('cetak',$character->id) }}">
                                    <i data-feather="upload" class="mr-50"></i>
                                    <span>Print</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="12" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $characters->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection

resources/views/kelas/kelas-xi-bdp.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Karakter Tables</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Karakter
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Karakter</h4>

      <a href="{{ route('characters.create') }}" class="btn btn-success">+ Tambah</a>

    </div>
    <form class="d-flex" action="{{ route('kelas.xi.bdp') }}" method="GET">
        {{ csrf_field() }}
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari nis siswa"></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
        <a class="btn btn-dark ag-grid-export-btn ml-auto mr-2" href="{{ route('export') }}">Export as Excel</a>
    </form>

    <div class="card-body">
    </div>

    <div class="table-responsive">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>NIS</th>
            <th>Nama</th>
            <th>Alias 1</th>
            <th>Alias 2</th>
            <th>Alias 3</th>
            <th>Alias 4</th>
            <th>Alias 5</th>
            <th>Catatan</th>
            <th>Tanggal Terbit</th>
            <th>Jurusan</th>
            <th>Kelas</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($characters as $character)
            <tr>
                <td>{{ $character->nis }}</td>
                <td>{{ $character->nama }}</td>
                <td>{{ $character->alias1->alias }}</td>
                <td>{{ $character->alias2->alias }}</td>
                <td>{{ $character->alias3->alias }}</td>
                <td>{{ $character->alias4->alias }}</td>
                <td>{{ $character->alias5->alias }}</td>
                <td>{{ $character->catatan }}</td>
                <td>{{ Carbon\Carbon::parse($character->penerbitan)->isoFormat('D MMMM Y') }}</td>
                <td>{{ $character->jurusan }}</td>
                <td>{{ $character->kelas }}</td>
                <td>
                        <form action="{{ route('characters.destroy',$character->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('characters.edit',$character->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>
                                  <a class="btn btn-success" href="{{ route('cetak',$character->id) }}">
                                    <i data-feather="upload" class="mr-50"></i>
                                    <span>Print</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="12" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $characters->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection

resources/views/kelas/kelas-xi-mmd.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Karakter Tables</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('welcome') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Table Karakter
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
          </div>
        </div>
      </div>


<!-- Table Hover Animation start -->
<div class="row" id="table-hover-animation">
<div class="col-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">List Karakter</h4>

      <a href="{{ route('characters.create') }}" class="btn btn-success">+ Tambah</a>

    </div>
    <form class="d-flex" action="{{ route('kelas.xi.mmd') }}" method="GET">
        {{ csrf_field() }}
        <div class="col-2"><div><input type="text" class="form-control" name="search" value="{{ request()->query('search') }}" placeholder="Cari nis siswa"></div></div>
        <button class="btn btn-primary"><i data-feather="search"></i></button>
        <a class="btn btn-dark ag-grid-export-btn ml-auto mr-2" href="{{ route('export') }}">Export as Excel</a>
    </form>

    <div class="card-body">
    </div>

    <div class="table-responsive">
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
      <table class="table table-hover-animation">
        <thead>
          <tr>
            <th>NIS</th>
            <th>Nama</th>
            <th>Alias 1</th>
            <th>Alias 2</th>
            <th>Alias 3</th>
            <th>Alias 4</th>
            <th>Alias 5</th>
            <th>Catatan</th>
            <th>Tanggal Terbit</th>
            <th>Jurusan</th>
            <th>Kelas</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @forelse ($characters as $character)
            <tr>
                <td>{{ $character->nis }}</td>
                <td>{{ $character->nama }}</td>
                <td>{{ $character->alias1->alias }}</td>
                <td>{{ $character->alias2->alias }}</td>
                <td>{{ $character->alias3->alias }}</td>
                <td>{{ $character->alias4->alias }}</td>
                <td>{{ $character->alias5->alias }}</td>
                <td>{{ $character->catatan }}</td>
                <td>{{ Carbon\Carbon::parse($character->penerbitan)->isoFormat('D MMMM Y') }}</td>
                <td>{{ $character->jurusan }}</td>
                <td>{{ $character->kelas }}</td>
                <td>
                        <form action="{{ route('characters.destroy',$character->id) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('characters.edit',$character->id) }}">
                                    <i data-feather="edit-2" class="mr-50"></i>
                                    <span>Edit</span>
                                  </a>
                                  <a class="btn btn-success" href="{{ route('cetak',$character->id) }}">
                                    <i data-feather="upload" class="mr-50"></i>
                                    <span>Print</span>
                                  </a>

                                  @csrf
                                  @method('DELETE')
                                  <button class="btn btn-danger"><i data-feather="trash" class="mr-50"></i><span>Delete</span></button>
                        </form>
                </td>
              </tr>
            @empty
            <tr>
                <td colspan="12" class="text-center">
                    <p class="text-center">No result found for query <strong>{{ request()->query('search') }}</strong></p>
                </td>
            </tr>
            @endforelse
        </tbody>
      </table>
    </div>

  </div>
  {!! $characters->appends(['search' => request()->query('search')])->links() !!}
</div>
</div>
<!-- Table head options end -->

      </div>
    </div>
  </div>
@endsection