routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\ChangePasswordController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\CharacterDeskripsiController;
use App\Http\Controllers\CharacterDibangunController;
use App\Http\Controllers\UserController;
use App\Models\Character;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [UserController::class, 'welcome'])->middleware('auth')->name('welcome');
Route::get('/profile', [UserController::class, 'profile'])->middleware('auth')->name('profile');
Route::post('/avatar-post', [UserController::class, 'update_profile'])->middleware('auth')->name('profile.post');
Route::post('/change-passowrd', [ChangePasswordController::class, 'changePassword'])->name('change.password');
Route::get('/print-character/{id}',[CharacterController::class, 'cetak'])->middleware('auth')->name('cetak');
Route::get('/characters/export/', [CharacterController::class, 'export'])->name('export');

Route::get('/karakter/rombel', [CharacterController::class, 'rombel'])->middleware('auth')->name('rombel');

Route::get('/karakter/kelas-bdp', [CharacterController::class, 'kelas_bdp'])->middleware('auth')->name('kelas.bdp');
Route::get('/karakter/kelas-mmd', [CharacterController::class, 'kelas_mmd'])->middleware('auth')->name('kelas.mmd');
Route::get('/karakter/kelas-otkp', [CharacterController::class, 'kelas_otkp'])->middleware('auth')->name('kelas.otkp');
Route::get('/karakter/kelas-htl', [CharacterController::class, 'kelas_htl'])->middleware('auth')->name('kelas.htl');
Route::get('/karakter/kelas-rpl', [CharacterController::class, 'kelas_rpl'])->middleware('auth')->name('kelas.rpl');
Route::get('/karakter/kelas-tbg', [CharacterController::class, 'kelas_tbg'])->middleware('auth')->name('kelas.tbg');
Route::get('/karakter/kelas-tkj', [CharacterController::class, 'kelas_tkj'])->middleware('auth')->name('kelas.tkj');

Route::get('/karakter/kelas-bdp-x', [CharacterController::class, 'kelas_x_bdp'])->middleware('auth')->name('kelas.x.bdp');
Route::get('/karakter/kelas-bdp-xi', [CharacterController::class, 'kelas_xi_bdp'])->middleware('auth')->name('kelas.xi.bdp');
Route::get('/karakter/kelas-bdp-xii', [CharacterController::class, 'kelas_xii_bdp'])->middleware('auth')->name('kelas.xii.bdp');

Route::get('/karakter/kelas-htl-x', [CharacterController::class, 'kelas_x_htl'])->middleware('auth')->name('kelas.x.htl');
Route::get('/karakter/kelas-htl-xi', [CharacterController::class, 'kelas_xi_htl'])->middleware('auth')->name('kelas.xi.htl');
Route::get('/karakter/kelas-htl-xii', [CharacterController::class, 'kelas_xii_htl'])->middleware('auth')->name('kelas.xii.htl');

Route::get('/karakter/kelas-mmd-x', [CharacterController::class, 'kelas_x_mmd'])->middleware('auth')->name('kelas.x.mmd');
Route::get('/karakter/kelas-mmd-xi', [CharacterController::class, 'kelas_xi_mmd'])->middleware('auth')->name('kelas.xi.mmd');
Route::get('/karakter/kelas-mmd-xii', [CharacterController::class, 'kelas_xii_mmd'])->middleware('auth')->name('kelas.xii.mmd');

Route::get('/karakter/kelas-otkp-x', [CharacterController::class, 'kelas_x_otkp'])->middleware('auth')->name('kelas.x.otkp');
Route::get('/karakter/kelas-otkp-xi', [CharacterController::class, 'kelas_xi_otkp'])->middleware('auth')->name('kelas.xi.otkp');
Route::get('/karakter/kelas-otkp-xii', [CharacterController::class, 'kelas_xii_otkp'])->middleware('auth')->name('kelas.xii.otkp');

Route::get('/karakter/kelas-rpl-x', [CharacterController::class, 'kelas_x_rpl'])->middleware('auth')->name('kelas.x.rpl');
Route::get('/karakter/kelas-rpl-xi', [CharacterController::class, 'kelas_xi_rpl'])->middleware('auth')->name('kelas.xi.rpl');
Route::get('/karakter/kelas-rpl-xii', [CharacterController::class, 'kelas_xii_rpl'])->middleware('auth')->name('kelas.xii.rpl');

Route::get('/karakter/kelas-tbg-x', [CharacterController::class, 'kelas_x_tbg'])->middleware('auth')->name('kelas.x.tbg');
Route::get('/karakter/kelas-tbg-xi', [CharacterController::class, 'kelas_xi_tbg'])->middleware('auth')->name('kelas.xi.tbg');
Route::get('/karakter/kelas-tbg-xii', [CharacterController::class, 'kelas_xii_tbg'])->middleware('auth')->name('kelas.xii.tbg');

Route::get('/karakter/kelas-tkj-x', [CharacterController::class, 'kelas_x_tkj'])->middleware('auth')->name('kelas.x.tkj');
Route::get('/karakter/kelas-tkj-xi', [CharacterController::class, 'kelas_xi_tkj'])->middleware('auth')->name('kelas.xi.tkj');
Route::get('/karakter/kelas-tkj-xii', [CharacterController::class, 'kelas_xii_tkj'])->middleware('auth')->name('kelas.xii.tkj');


Route::resource('characters', CharacterController::class)->middleware('auth');
Route::resource('character-dibangun', CharacterDibangunController::class)->middleware('auth');

app/Models/Character.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Character extends Model
{
    use HasFactory;

    protected $table = 'characters';
    protected $primaryKey = 'id';
    protected $guarded = [];
    public $incrementing = false;


    public static function getCharacters(){
        $records = DB::table('characters')->select('nis', 'nama', 'integritas', 'religius', 'nasionalis', 'mandiri', 'gotong_royong', 'catatan', 'penerbitan')->get()->toArray();
        return $records;
    }

    public function alias1()
    {
        return $this->belongsTo(CharacterDibangun::class, 'alias_1', 'id');
    }

    public function alias2()
    {
        return $this->belongsTo(CharacterDibangun::class, 'alias_2', 'id');
    }

    public function alias3()
    {
        return $this->belongsTo(CharacterDibangun::class, 'alias_3', 'id');
    }

    public function alias4()
    {
        return $this->belongsTo(CharacterDibangun::class, 'alias_4', 'id');
    }

    public function alias5()
    {
        return $this->belongsTo(CharacterDibangun::class, 'alias_5', 'id');
    }

}

app/Http/Controllers/CharacterController.php
<?php

namespace App\Http\Controllers;

use App\Models\Character;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Exports\CharactersExport;
use App\Models\CharacterDeskripsi;
use App\Models\CharacterDibangun;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Str;

class CharacterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('nis', 'LIKE', "%{$search}%")->orWhere('nama', 'LIKE', "%{$search}%")->paginate(5);
        }else {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->paginate(5);
        }

        return view('characters.index', [
            'characters' => $characters,
        ])
        ->with('i');
    }

    public function cetak($id)
    {
        $character = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->findOrFail($id);

        return view('characters.cetak', compact('character'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $juduls = CharacterDibangun::get();

        return view('characters.create', compact('juduls'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nis' => 'required|numeric|unique:characters',
            'nama' => 'required|max:50',
            'alias_1' => 'required',
            'alias_2' => 'required',
            'alias_3' => 'required',
            'alias_4' => 'required',
            'alias_5' => 'required',
            'catatan' => 'required',
            'penerbitan' => 'required',
            'jurusan' => 'required',
            'kelas' => 'required'
        ]);

        $character = new Character;
        $character->id = Str::random(60);
        $character->nis = $request->nis;
        $character->nama = $request->nama;
        $character->alias_1 = $request->alias_1;
        $character->alias_2 = $request->alias_2;
        $character->alias_3 = $request->alias_3;
        $character->alias_4 = $request->alias_4;
        $character->alias_5 = $request->alias_5;
        $character->catatan = $request->catatan;
        $character->penerbitan = $request->penerbitan;
        $character->jurusan = $request->jurusan;
        $character->kelas = $request->kelas;
        $character->save();

        return redirect()->route('characters.index')->with('success', 'Karakter siswa berhasil dibuat !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $juduls = CharacterDibangun::all();
        $character = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->findOrFail($id);

        return view('characters.edit', compact('character', 'juduls'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nis' => 'required|numeric',
            'nama' => 'required|max:50',
            'alias_1' => 'required',
            'alias_2' => 'required',
            'alias_3' => 'required',
            'alias_4' => 'required',
            'alias_5' => 'required',
            'catatan' => 'required',
            'penerbitan' => 'required',
            'jurusan' => 'required',
            'kelas' => 'required'
        ]);

        $character = Character::findOrFail($id);
        $character->update($request->all());

        return redirect()->route('characters.index')->with('success', 'Karakter siswa berhasil diupdate!');
    }

    public function export()
    {
        return Excel::download(new CharactersExport, 'characters.xlsx');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $character = Character::findOrFail($id);
        $character->delete();

        return redirect()->route('characters.index')->with('success', 'Karakter siswa berhasil dihapus!');
    }

    public function rombel()
    {
        return view('characters.rombel');
    }

    public function kelas_bdp()
    {
        return view('kelas.kelas-bdp');
    }

    public function kelas_htl()
    {
        return view('kelas.kelas-htl');
    }

    public function kelas_mmd()
    {
        return view('kelas.kelas-mmd');
    }

    public function kelas_otkp()
    {
        return view('kelas.kelas-otkp');
    }

    public function kelas_rpl()
    {
        return view('kelas.kelas-rpl');
    }

    public function kelas_tbg()
    {
        return view('kelas.kelas-tbg');
    }

    public function kelas_tkj()
    {
        return view('kelas.kelas-tkj');
    }




    public function kelas_x_tkj()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'X')->where('jurusan', '=', 'Teknik Komputer dan Jaringan')->where('nis', 'LIKE', "%{$search}%")->orWhere('nama', 'LIKE', "%{$search}%")->paginate(5);
        }else {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'X')->where('jurusan', '=', 'Teknik Komputer dan Jaringan')->paginate(5);
        }

        return view('kelas.kelas-x-tkj', [
            'characters' => $characters,
        ])
        ->with('i');
    }

    public function kelas_xi_tkj()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'XI')->where('jurusan', '=', 'Teknik Komputer dan Jaringan')->where('nis', 'LIKE', "%{$search}%")->orWhere('nama', 'LIKE', "%{$search}%")->paginate(5);
        }else {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'XI')->where('jurusan', '=', 'Teknik Komputer dan Jaringan')->paginate(5);
        }

        return view('kelas.kelas-xi-tkj', [
            'characters' => $characters,
        ])
        ->with('i');
    }

    public function kelas_xii_tkj()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'XII')->where('jurusan', '=', 'Teknik Komputer dan Jaringan')->where('nis', 'LIKE', "%{$search}%")->orWhere('nama', 'LIKE', "%{$search}%")->paginate(5);
        }else {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'XII')->where('jurusan', '=', 'Teknik Komputer dan Jaringan')->paginate(5);
        }

        return view('kelas.kelas-xii-tkj', [
            'characters' => $characters,
        ])
        ->with('i');
    }

    public function kelas_x_bdp()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'X')->where('jurusan', '=', 'Bisnis Daring dan Pemasaran')->where('nis', 'LIKE', "%{$search}%")->orWhere('nama', 'LIKE', "%{$search}%")->paginate(5);
        }else {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'X')->where('jurusan', '=', 'Bisnis Daring dan Pemasaran')->paginate(5);
        }

        return view('kelas.kelas-x-bdp', [
            'characters' => $characters,
        ])
        ->with('i');
    }

    public function kelas_xi_bdp()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'XI')->where('jurusan', '=', 'Bisnis Daring dan Pemasaran')->where('nis', 'LIKE', "%{$search}%")->orWhere('nama', 'LIKE', "%{$search}%")->paginate(5);
        }else {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'XI')->where('jurusan', '=', 'Bisnis Daring dan Pemasaran')->paginate(5);
        }

        return view('kelas.kelas-xi-bdp', [
            'characters' => $characters,
        ])
        ->with('i');
    }

    public function kelas_xii_bdp()
    {
        Paginator::useBootstrap();
        $search = request()->query('search');

        if($search)
        {
            $characters = Character::with('alias1', 'alias2', 'alias3', 'alias4', 'alias5')->where('kelas', '=', 'XII')->where('jurusan', '=', 'Bisnis Daring dan Pemasaran')->where('nis', 'LIKE', "%{$search}%")->orWhere('nama', 'LIKE', "%{$search}%")->paginate(5);
        }else {

resources/views/characters/create.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Form Validation</h2>
              <div class="breadcrumb-wrapper">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="index-2.html">Home</a>
                  </li>
                  <li class="breadcrumb-item"><a href="#">Forms</a>
                  </li>
                  <li class="breadcrumb-item active">Form Validation
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
          <div class="form-group breadcrumb-right">
            <div class="dropdown">

            </div>
          </div>
        </div>
      </div>
      <div class="content-body"><!-- Validation -->
<section class="bs-validation">
<div class="row">
  <!-- Bootstrap Validation -->
  <div class="col-md-12 col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Bootstrap Validation</h4>
      </div>
      <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form class="needs-validation" method="POST" action="{{ route('characters.store') }}">
            @csrf
            <div class="form-group">
                <label class="form-label" for="basic-addon-name">Nomor Induk Siswa(NIS)</label>

                <input
                  type="number"
                  id="basic-addon-name"
                  class="form-control"
                  placeholder="Nomor Induk"
                  name="nis"
                  aria-describedby="basic-addon-name"
                  required
                />
              </div>
              <div class="form-group">
                <label class="form-label" for="basic-default-email1">Nama Lengkap</label>
                <input
                  type="text"
                  id="basic-default-email1"
                  class="form-control"
                  name="nama"
                  placeholder="Nama Lengkap"
                  required
                />
              </div>
          <div class="form-group">
            <label class="form-label" for="alias_1">Alias 1</label>
            <select class="form-control" name="alias_1" id="alias_1" required>
                <option value="" disabled selected>Pilih Alias 1</option>
                @foreach ($juduls as $judul)
                <option value="{{ $judul->id }}">{{ $judul->alias }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="alias_1">Alias 2</label>
            <select class="form-control" name="alias_2" id="alias_2" required>
                <option value="" disabled selected>Pilih Alias 1</option>
                @foreach ($juduls as $judul)
                <option value="{{ $judul->id }}">{{ $judul->alias }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="alias_3">Alias 3</label>
            <select class="form-control" name="alias_3" id="alias_3" required>
                <option value="" disabled selected>Pilih Alias 3</option>
                @foreach ($juduls as $judul)
                <option value="{{ $judul->id }}">{{ $judul->alias }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="alias_1">Alias 4</label>
            <select class="form-control" name="alias_4" id="alias_4" required>
                <option value="" disabled selected>Pilih Alias 4</option>
                @foreach ($juduls as $judul)
                <option value="{{ $judul->id }}">{{ $judul->alias }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="alias_5">Alias 5</label>
            <select class="form-control" name="alias_5" id="alias_5" required>
                <option value="" disabled selected>Pilih Alias 5</option>
                @foreach ($juduls as $judul)
                <option value="{{ $judul->id }}">{{ $judul->alias }}</option>
                @endforeach
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="catatan">Catatan</label>
            <select class="form-control" name="catatan" id="catatan" required>
                <option value="" disabled selected>Pilih Deskripsi Catatan</option>
                <option value="Ananda menunjukkan perkembangan karakter yang BAIK pada pembelajaran semester ini.">Ananda menunjukkan perkembangan karakter yang BAIK pada pembelajaran semester ini.</option>
                <option value="Ananda menunjukkan perkembangan karakter yang SANGAT BAIK pada pembelajaran semester ini.">Ananda menunjukkan perkembangan karakter yang SANGAT BAIK pada pembelajaran semester ini.</option>
                <option value="Ananda menunjukkan perkembangan karakter yang CUKUP BAIK pada pembelajaran semester ini.">Ananda menunjukkan perkembangan karakter yang CUKUP BAIK pada pembelajaran semester ini.</option>
                <option value="Ananda menunjukkan perkembangan karakter yang KURANG BAIK pada pembelajaran semester ini.">Ananda menunjukkan perkembangan karakter yang KURANG BAIK pada pembelajaran semester ini.</option>
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="penerbitan">Tanggal Penerbitan</label>
            <input
            type="date"
            id="penerbitan"
            class="form-control"
            placeholder="Tanggal Penerbitan"
            name="penerbitan"
            aria-describedby="basic-addon-name"
            required
          />
          </div>
          <div class="form-group">
            <label class="form-label" for="Jurusan">Jurusan</label>
            <select class="form-control" name="jurusan" id="Jurusan" required>
                <option value="" disabled selected>Pilih Jurusan</option>
                <option value="Bisnis Daring dan Pemasaran">Bisnis Daring dan Pemasaran</option>
                <option value="Multimedia">Multimedia</option>
                <option value="Otomatisasi Tatakelola dan Perkantoran">Otomatisasi Tatakelola dan Perkantoran</option>
                <option value="Perhotelan">Perhotelan</option>
                <option value="Rekayasa Perangkat Lunak">Rekayasa Perangkat Lunak</option>
                <option value="Tataboga">Tataboga</option>
                <option value="Teknik Komputer dan Jaringan">Teknik Komputer dan Jaringan</option>
              </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="kelas">Kelas</label>
            <select class="form-control" name="kelas" id="kelas" required>
                <option value="" disabled selected>Pilih Kelas</option>
                <option value="X">X</option>
                <option value="XI">XI</option>
                <option value="XII">XII</option>
              </select>
          </div>
          <div class="alert alert-danger mt-1 alert-validation-msg" role="alert">
            <div class="alert-body">
              <i data-feather="info" class="mr-50 align-middle"></i>
              <span><strong>Note:</strong> Harap memilih semua pilihan lagi karena web ini masih dalam tahap test beta!</span>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- /Bootstrap Validation -->
</div>
</section>
<!-- /Validation -->

      </div>
    </div>
  </div>
@endsection

resources/views/characters/rombel.blade.php
@extends('layouts.default')

@section('content')
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
      <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
          <div class="row breadcrumbs-top">
            <div class="col-12">
              <h2 class="content-header-title float-left mb-0">Pilih Jurusan</h2>
            </div>
          </div>
        </div>
      </div>

            <div class="text-center">
                <a class="btn btn-primary btn-lg col-md-8 mt-5" href="{{ route('kelas.bdp') }}">Bisnis Daring dan Pemasaran</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.mmd') }}">Multimedia</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.otkp') }}">Otomatisasi Tatakelola dan Perkantoran</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.htl') }}">Perhotelan</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.rpl') }}">Rekayasa Perangkat Lunak</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.tbg') }}">Tataboga</a>

                <a class="btn btn-primary btn-lg col-md-8 mt-2" href="{{ route('kelas.tkj') }}">Teknik Komputer dan Jaringan</a>
            </div>


      </div>
    </div>
  </div>
@endsection